### ISSUE TITLE
can't find "{root}/lib" folder

### ISSUE THREAD

**Issue by truwind** [danishin/webrtc-automator#1]
한국분이신것 같아서 한글로 문의 드립니다.
(혹시 한국분이 아니시면 영어로 다시 질문하겠습니다.)
제가 scala는 처음 접하는 상태여서 일단 지인들에게 물어 물어 어떻게 스칼라도 맥에 설치해서 
"fetch_ios.sh"를 실행하면 아래와 같은 에러가 나오고 있습니다.
([Error] Cannot run program "/bin/sh" (in directory "/Users/truwind/Develop/test/amr64/danishin_fat/webrtc-build-master/lib"): error=2, No such file or directory)
제가 스칼라를 잘못 설치한것인지? 아니면 빌드 환경이 문제가 있는 것인지요?
# 

Last login: Tue Feb 16 09:38:02 on ttys001
truwindui-MacBook-Retina:~ truwind$ cd /Users/truwind/Develop/test/amr64/danishin_fat/webrtc-build-master 
truwindui-MacBook-Retina:webrtc-build-master truwind$ chmod 755 bin/*.sh
truwindui-MacBook-Retina:webrtc-build-master truwind$ bin/fetch_ios.sh
[info] Loading project definition from /Users/truwind/Develop/test/amr64/danishin_fat/webrtc-build-master/project
[info] Set current project to webrtc_build (in build file:/Users/truwind/Develop/test/amr64/danishin_fat/webrtc-build-master/)
[info] Updating {file:/Users/truwind/Develop/test/amr64/danishin_fat/webrtc-build-master/}webrtc-build-master...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 7 Scala sources to /Users/truwind/Develop/test/amr64/danishin_fat/webrtc-build-master/target/scala-2.11/classes...
[info] Running Application fetch ios

---
## Fetch Entire WebRTC library for ios

Clone depot_tools
## Executing...
- Command: /bin/sh -c git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
- CWD: /Users/truwind/Develop/test/amr64/danishin_fat/webrtc-build-master/lib
- Env Vars: 

---

[Error] Cannot run program "/bin/sh" (in directory "/Users/truwind/Develop/test/amr64/danishin_fat/webrtc-build-master/lib"): error=2, No such file or directory

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"
java.lang.RuntimeException: Nonzero exit code: 1
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error](compile:run) Nonzero exit code: 1
[error] Total time: 7 s, completed 2016. 2. 16 오전 9:55:34
# truwindui-MacBook-Retina:webrtc-build-master truwind$

**Comment by danishin** [comment]
@truwind  네 한국인 맞습니다 한국말이 좀 어눌하긴 하지만.. 이상하게 이메일 노티피케이션을 못받았네요.

보니깐 버그네요 `lib` folder 를 `.gitignore` 에 넣는 바람에 그런 것 같네요. - e0c101fb125a81768575a

지금 있는 곳 인터넷이 느려서 아직 `fetch` 는 테스트를 못했습니다. 해보고 안되시면 알려주세요!
